# 多线程锁的问题



## 两个普通同步方法，没有暂停

```java
class Phone {
    public synchronized void sendOne() throws Exception {
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(200);

        new Thread(() -> {
            try {
                phone.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}


```

运行结果

```java
---sendOne
---sendTwo
```

这是因为中间加了sleep，所以才会出现这样的情况。一般来说，不能确定。





## 两个普通同步方法，One()暂停

```java
class Phone {
    public synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(200);

        new Thread(() -> {
            try {
                phone.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}


```

运行结果：

```java
结果：
---sendOne
---sendTwo
```

原因：**一个对象里面如果有多个synchronized方法，某一时刻内，只能有一个线程去调用其中的一个synchronized方法。因为synchronized锁的是当前对象this，被锁定后，其它线程都不能进入到当前对象的其它synchronized方法。**



## 普通方法hello()和同步方法One()，One()暂停

```java
class Phone {
    public synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                // phone.sendTwo();
                phone.hello();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}

```

运行结果：

```java
----hello
---sendOne
```

原因：加的普通方法和同步锁没有关系



## 两个对象，One()暂停

```java
class Phone {
    public synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();
        Phone phone2 = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                // phone.sendTwo();
                // phone.hello();
                phone2.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}

```

运行结果：

```java
---sendTwo
---sendOne
```

原因：两个对象，不是同一个锁。



## 两个静态同步方法，同一对象，One()暂停

```java
class Phone {
    public static synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public static synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();
        Phone phone2 = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                phone.sendTwo();
                // phone.hello();
                // phone2.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}


```

运行结果：

```java
结果：
---sendOne
---sendTwo
```

原因：锁的不是实例，而是phone.class文件（相当于锁的是模板）

## 两个静态同步方法，两个对象，One()暂停

```java
class Phone {
    public static synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public static synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();
        Phone phone2 = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                // phone.sendTwo();
                // phone.hello();
                phone2.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}
```

运行结果：

```java
---sendOne
---sendTwo
```

原因：锁的不是实例，而是phone.class文件（相当于锁的是模板）

## One()静态同步方法，Two()普通同步方法，一个对象

```java
class Phone {
    public static synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();
        Phone phone2 = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                phone.sendTwo();
                // phone.hello();
                // phone2.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}

```

运行结果：

```java
---sendTwo
---sendOne
```

原因：静态同步方法锁的是class，普通同步方法锁的是对象，不冲突，所以先打印Two

## One()静态同步方法，Two()普通同步方法，两个对象

```java
class Phone {
    public static synchronized void sendOne() throws Exception {
        try {
            TimeUnit.SECONDS.sleep(4);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("---sendOne");
    }

    public synchronized void sendTwo() throws Exception {
        System.out.println("---sendTwo");
    }

    public void hello() {
        System.out.println("----hello");
    }
}
public class Lock8 {
    public static void main(String[] args) throws InterruptedException {
        Phone phone = new Phone();
        Phone phone2 = new Phone();

        new Thread(() -> {
            try {
                phone.sendOne();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "One").start();

        Thread.sleep(100);

        new Thread(() -> {
            try {
                // phone.sendTwo();
                // phone.hello();
                phone2.sendTwo();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, "Two").start();
    }
}
```

运行结果：

```java
---sendTwo
---sendOne
```



原因：静态同步方法锁的是class，普通同步方法锁的是对象，不冲突，所以先打印Two

